// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxbzggftzldttlhtvcej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4YnpnZ2Z0emxkdHRsaHR2Y2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjM5NTgsImV4cCI6MjA2NDU5OTk1OH0.pkqQ_Z4WC1CLxpW8NVnZwBFol_Msi7HndUMG92qwQlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});